name: Pull request update

on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: read

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PR_UPDATE_TOKEN }}" | gh auth login --with-token

      - name: Update PR branches
        run: |
          prs=$(gh pr list --state open --base main --json number,headRefName -q '.[] | [.number, .headRefName] | @tsv')

          echo "-----------------Git config----------------------------"
          git config --list
          echo "-----------------Git config----------------------------"

          echo "-----------------Git status----------------------------"
          git status
          echo "-----------------Git status----------------------------"

          while IFS=$'\t' read -r number branch; do
            echo "Updating PR #$number (branch: $branch)"

            git fetch origin "$branch"
            git checkout "$branch"

            if git merge origin/main --no-edit; then
              echo "git remote set-url origin https://x-access-token:${{ secrets.PR_UPDATE_TOKEN }}@github.com/${{ github.repository }}.git"
              git remote set-url origin https://x-access-token:${{ secrets.PR_UPDATE_TOKEN }}@github.com/${{ github.repository }}.git
              git push origin HEAD:$branch
              echo "✅ Updated $branch"
            else
              echo "❌ Merge conflict on $branch — skipped."
              git merge --abort
            fi
          done <<< "$prs"

