name: Pull request update

on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: write
  actions: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Update ALL THE PRS! 🎉
        uses: castastrophe/actions-pr-auto-update


