name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: 'Dry run'
        default: true

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set current branch
        run: |
          # Update the .releaserc.json file with the current branch name
          current_branch=$(git branch --show-current)
          jq --arg branch "$current_branch" '.branches |= map(if . == "CURRENT_BRANCH" then $branch else . end)' .releaserc.json > .releaserc.json.tmp
          mv .releaserc.json.tmp .releaserc.json
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run=${{ github.event.inputs.dry-run }}
          