name: Release

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: 'Dry run'
        default: true

jobs:
  semantic-release:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set current branch
        run: |
          # Update the .releaserc.json file with the current branch name. 
          # Needed for semantic-release to work with maintenace branches.

          current_branch=$(git branch --show-current)
          if [[ $current_branch == "pre/rc" ]]; then
            exit 0
          fi
          range="${current_branch#release/rel-}.x"

          jq --arg branch "$current_branch" --arg range "$range" '
            .branches |= map(if type == "object" and .name == "CURRENT_BRANCH"
              then .name = $branch | .range = $range
              else . end)' \
            .releaserc.json > .releaserc.json.tmp

          mv .releaserc.json.tmp .releaserc.json
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --dry-run=${{ github.event.inputs.dry-run }}
          